/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-07-16 01:27:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jqueryAddress;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class zipCheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src = \"https://code.jquery.com/jquery-3.5.1.min.js\"></script> <!-- jquery쓰겠다 -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t//getJSON함수 사용\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"#send\").on(\"click\",function(){\r\n");
      out.write("\t\t\t$.getJSON(\"zipCheckPro.jsp\",{\"dong\":$(\"#dong\").val()}, //JSON 사용\r\n");
      out.write("\t\t\t\tfunction(data){//콜백함수\r\n");
      out.write("\t\t\t\tvar htmlStr=\"<table>\";\r\n");
      out.write("\t\t\t$.each(data,function(key,val){ //JSON은 파싱 O -> each문 가넝~\r\n");
      out.write("\t\t\t\thtmlStr+= \"<tr>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+val.zipcode+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+val.sido+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+val.gugun+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+val.dong+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+val.bunji+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"</tr>\";\r\n");
      out.write("\t\t\t})\t\t\t\r\n");
      out.write("\t\t\thtmlStr+=\"</table>\";\r\n");
      out.write("\t\t\t$(\"#area\").html(htmlStr);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t);\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t//get함수 사용\r\n");
      out.write("\t$(\"#getsend\").click(function(){\r\n");
      out.write("\t\t$.get(\"zipCheckPro.jsp\",{\"dong\":$(\"#dong\").val()},\r\n");
      out.write("\t\t\tfunction(data){\r\n");
      out.write("\t\t\tvar htmlStr=\"<table>\";\r\n");
      out.write("\t\t\td = $.parseJSON(data); //파싱\r\n");
      out.write("\t\t\tfor(var i=0; i<d.length;i++){ //foreach문 쓰기위해 파싱\r\n");
      out.write("\t\t\t\thtmlStr+=\"<tr>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+d[i].zipcode+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+d[i].sido+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+d[i].gugun+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+d[i].dong+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"<td>\"+d[i].bunji+\"</td>\";\r\n");
      out.write("\t\t\t\thtmlStr+=\"</tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\thtmlStr+=\"</table>\";\r\n");
      out.write("\t\t\t$(\"#area\").html(htmlStr);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t);//get\r\n");
      out.write("\t});//getsend\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#area\").on(\"click\",\"tr\",function(){ //area와 1줄인 tr과 클릭 이벤트 연결\r\n");
      out.write("\t\tvar address= $(\"td:eq(1)\",this).text()+\" \"+\r\n");
      out.write("\t\t\t\t     $(\"td:eq(2)\",this).text()+\" \"+\r\n");
      out.write("\t\t             $(\"td:eq(3)\",this).text()+\" \"+\r\n");
      out.write("\t\t             $(\"td:eq(4)\",this).text();\r\n");
      out.write("\t                 $(opener.document).find(\"#zipcode\").val($(\"td:eq(0)\",this).text());\r\n");
      out.write("\t                 $(opener.document).find(\"#addr\").val(address);\r\n");
      out.write("\t\tself.close();\r\n");
      out.write("\t});\r\n");
      out.write("});//document\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>동이름 입력 <input type=\"text\" name=\"dong\" id=\"dong\">\r\n");
      out.write("\t<input type=\"button\" id=\"send\" value=\"검색\">\r\n");
      out.write("\t<input type=\"button\" id=\"getsend\" value=\"get검색\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div id=\"area\"></div> <!-- table끝난 후, div -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
